export { default as image1 } from './1.png'
export { default as image2 } from './2.png'
export { default as image3 } from './3.png'
export { default as image4 } from './4.png'
export { default as image5 } from './5.png'
