import { AngularLogo, Lego, Toolbox } from '@phosphor-icons/react'

export const data = {
  basics: {
    github: 'https://vladut-pop.github.io/portfolio-app/',
    name: 'Vlǎduț Traian POP',
    email: 'vladpop@ucm.es',
    phone: '',
    picture:
      'https://storage.rxresu.me/cm1v20mmu2ceqmtv50adxdxvw/pictures/cm1v20mmu2ceqmtv50adxdxvw.jpg',
    headline: 'Frontend Developer',
    location: 'Baia Mare, Romania',
  },
  skills: [
    {
      icon: <AngularLogo size={24} weight="thin" />,
      heading: 'Frontend frameworks',
      subheading: 'React, Vue',
    },
    {
      icon: <Lego size={24} weight="thin" />,
      heading: 'Design System',
      subheading: 'Reusable components',
    },
    {
      icon: <Toolbox size={24} weight="thin" />,
      heading: 'Frontend tools',
      subheading: 'Typescript,',
    },
  ],
  experience: [
    {
      company: 'BoatYardX',
      logo: '',
      position: 'Frontend Developer',
      startDate: '2021-06-01',
      endDate: 'Current',
      summary: 'Creating a set of standards for design and code along with reusable UI components.',
      keys: [
        'React',
        'CSS',
        'SASS',
        'HTML',
        'TS',
        'Testing',
        'Azure',
        'CLI’s',
        'Eslint',
        'git flow',
        'Storybook',
        'Percy',
      ],
      projects: [
        {
          name: 'Design System',
          startDate: '2021-06-01',
          endDate: 'Current',
          summary:
            'Creating a set of standards for design and code along with reusable UI components.',
          keys: [
            'React',
            'CSS',
            'SASS',
            'HTML',
            'TS',
            'Testing',
            'Azure',
            'CLI’s',
            'Eslint',
            'git flow',
            'Storybook',
            'Percy',
          ],
        },
        {
          name: 'TSU',
          startDate: '2022-02-01',
          endDate: '2022-05-31',
          summary: 'Supporting entrepreneurs to grow their business from idea to invoice.',
          keys: [
            'React',
            'Laravel PHP',
            'Node.js',
            'mySQL',
            'AWS',
            'CSS',
            'HTML',
            'JS',
            'Eslint',
            'git flow',
          ],
        },
        {
          name: 'R3M',
          startDate: '2021-06-01',
          endDate: '2022-02-28',
          summary:
            'Developing an application with multiple functions and systems for fleet status.',
          keys: ['Vue.js', 'CSS', 'HTML', 'JS', 'Eslint', 'git flow'],
        },
      ],
    },
    {
      company: 'Q_Perior',
      logo: '',
      position: 'Frontend Developer',
      startDate: '2020-08-01',
      endDate: '2021-06-30',
      summary: 'Facilitating access to special medication across multiple countries.',
      keys: [
        'Cypress',
        'CSS',
        'HTML',
        'JS',
        'React',
        'Redux',
        'Material-UI',
        'Bootstrap',
        'LightHouse',
      ],
      projects: [
        {
          name: 'PatientStrength',
          startDate: '2020-08-01',
          endDate: '2021-06-30',
          summary: 'Facilitating access to special medication across multiple countries.',
          keys: [
            'Cypress',
            'CSS',
            'HTML',
            'JS',
            'React',
            'Redux',
            'Material-UI',
            'Bootstrap',
            'LightHouse',
          ],
        },
        {
          name: 'AppX',
          startDate: '2020-11-01',
          endDate: '2020-12-31',
          summary: 'Developing a customized Fiori Application for worklog approval.',
          keys: ['Fiori App', 'Mockup', 'OData services', 'Proof of Concept'],
        },
        {
          name: 'Challenge Platform',
          startDate: '2020-05-01',
          endDate: '2020-06-30',
          summary:
            'Creating an internal application to support the development of new technologies.',
          keys: ['MongoDB', 'Aurelia JS', 'CSS', 'HTML', 'JS'],
        },
        {
          name: 'Tender',
          startDate: '2020-04-01',
          endDate: '2020-05-31',
          summary: 'Developing a prototype app to present graphical information to the user.',
          keys: ['D3', 'React'],
        },
        {
          name: 'MES',
          startDate: '2019-06-01',
          endDate: '2020-03-31',
          summary: 'Developing a customized MES system based on SAP MM and PP.',
          keys: ['SAP UI5', 'Fiori', 'Odata', 'Mockups', 'JavaScript', 'CSS', 'Proof of Concept'],
        },
        {
          name: 'Faktura Intern',
          startDate: '2019-05-01',
          endDate: '2020-06-30',
          summary: 'Optimizing the invoicing process and the generation of activity reports.',
          keys: ['SAP UI5', 'Fiori', 'HTTP requests', 'CSS', 'HTML', 'Odata'],
        },
      ],
    },
  ],
}
